# Import numpy


# العمليات الرياضية 

In [3]:
import numpy as np  
from  numpy import *

In [2]:
!pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 217.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/59.7 kB 187.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/59.7 kB 187.9 kB/s eta 0:00:01
     -------------------------- ----------- 41.0/59.7 kB 140.3 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/59.7 kB 163.8 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 176.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB 1.4 MB/s eta 0:00:10
   ---------------------------------------- 0.1/12.9 MB 825.8 kB/s eta 0:00:16
   ---------------------------------------- 0.1/12.9 MB 825.8 kB/s eta 0:00:16
   ---------------------------------------- 0.1/12.9 MB 825.8 kB/s eta


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
a = sin(30)
b = cos(30)
c = tan(30)

print(a , b , c)

 

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [4]:
a = sin(30*np.pi/180)
b = cos(30*np.pi/180)
c = tan(30*np.pi/180)

print(a)
print(b)
print(c)


0.49999999999999994
0.8660254037844387
0.5773502691896257


In [5]:
a = sin(deg2rad(30))
b = cos(deg2rad(30))
c = tan(deg2rad(30))

print(a)
print(b)
print(c)


0.49999999999999994
0.8660254037844387
0.5773502691896257


In [11]:
a = round(3.8528)
b = round(3.68528,1)   
c = round(3.68528,2)
d = round(3.68528,3)
e = round(3.68528,4)

print(a)
print(b)
print(c)
print(d)
print(e)


4
3.7
3.69
3.685
3.6853


In [12]:
a = floor(3.68528)
b = ceil(3.68528)

print(a)
print(b)


3.0
4.0


In [13]:
a = mod(20,7) #  20%7 # 20/7 =   2.6868- 2= 0.686*7 =6 
b = power(2,5)

print(a)
print(b)


6
32


# كتابة المصفوفات

In [14]:
a = [2,3,6,5,4,7,8]
b = np.array(a)

print(a)
print(b)


[2, 3, 6, 5, 4, 7, 8]
[2 3 6 5 4 7 8]


In [15]:
#how builtin function can work
flat_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
rows = 3
cols = 3
matrix = []
for i in range(rows):
    row = []
    for j in range(cols):
        row.append(flat_list[i * cols + j])    #m*n
    matrix.append(row)
print(matrix)    

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
a = [[1,2,3],[5,3,6],[9,6,5]]
b = array(a)
print(a)
print(b)


[[1, 2, 3], [5, 3, 6], [9, 6, 5]]
[[1 2 3]
 [5 3 6]
 [9 6 5]]


In [19]:
a = empty((3,2))

print(a)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
a = random.uniform(1,10)
b = random.uniform(1,10,20)

print(a)
print('-------------------------')
print(b)
print('-------------------------')


2.4809919344486953
-------------------------
[5.89152875 3.38811688 6.58677293 4.54753505 4.36857336 3.54260369
 1.1566261  2.25974107 3.65243744 7.43984666 1.13623248 3.29894007
 4.67772241 7.46123942 8.90397326 6.27102427 8.9501515  8.92214682
 7.90301799 7.84740065]
-------------------------


In [21]:
#●	بأمر random.random   يمكن عمل مصفوفة بارقام عشوائية تتراوح بين 0 و 1   
a =random.random((2,3))

print(a)


[[0.66423677 0.95943206 0.43643431]
 [0.44549245 0.05377409 0.50851831]]


In [22]:
#●	أمر random.normal  بأتي بالتوزيع الطبيعي لارقام بين الصفر و 1 , عدد 10 ارقام   
a =random.normal(0,1,10)

print(a)


[ 0.2031266   0.16567484 -0.75330167  0.21573906  0.94274554  0.80946562
  0.93732467 -0.89373687 -0.89214717 -0.41671944]


In [25]:
#●	بأمر  random.randint  يمكن تحديد رقم عشوائي صحيح بين 0 و 150 
a =  random.randint(150)

print(a)


32


In [30]:
#●	و   يمكن تحديد 7 ارقام صحيحة عشوائية من 0 الي 5 
a =random.randint(5, size=7)                                    

print(a)


[4 1 2 4 2 0 0]


In [31]:
#●	ولو تم كتابة رقمين فتكون الارقام تتراوح بين الرقمين  
a =random.randint(5,20, size=7)

print(a)


[ 9  6  7 14 14  8  8]


In [32]:
#●	ويمكن عمل مصفوفة ارقام صحيحة بين 0 و 
a = random.randint(0, 10, (3, 3))

print(a)


[[3 4 9]
 [3 4 6]
 [2 6 0]]


In [33]:
#●	او تلات ابعاد  
a = random.randint(5,10, size=(3, 4, 5))

print(a)


[[[5 8 8 5 8]
  [8 5 5 8 6]
  [9 9 9 6 5]
  [6 6 9 9 7]]

 [[5 9 8 5 9]
  [5 8 9 7 5]
  [7 6 9 8 5]
  [7 9 6 9 5]]

 [[5 9 9 5 5]
  [7 6 8 5 6]
  [6 6 8 9 7]
  [7 8 5 7 9]]]


In [34]:
#●	او يتعمل صف ارقام و يتم تشكيلها  
a = random.randint(1,60,25)
b = reshape(a,(5,5))

print(a)
print(b)


[18 32 45 54 12  3 51  5 27 41 49 52  5 27 32 46 40 34 55 58 24 18 31 38
 33]
[[18 32 45 54 12]
 [ 3 51  5 27 41]
 [49 52  5 27 32]
 [46 40 34 55 58]
 [24 18 31 38 33]]


In [35]:
#●	هنا يعمل ارقام عشوائية من 0 لـ 1 بالعدد المطلوب  
a = random.rand(15)

print(a)


[0.66198313 0.54776993 0.64838361 0.92573594 0.37535138 0.62362431
 0.13607354 0.58457123 0.23961075 0.89369459 0.47960894 0.0053955
 0.93338502 0.381642   0.71309432]


In [36]:
#●	او مصفوفة بعدين  
a = random.rand(5,3)

print(a)


[[0.9263107  0.58603509 0.13166311]
 [0.71420114 0.86965828 0.45448051]
 [0.43556884 0.73587795 0.23970438]
 [0.73785574 0.73945196 0.6070607 ]
 [0.9440588  0.24917415 0.45074002]]


In [37]:
#●	او تلات ابعاد  
a = random.rand(5,3,2)

print(a)


[[[0.20166409 0.76387811]
  [0.91931988 0.44883809]
  [0.42395475 0.68136267]]

 [[0.08998398 0.96170802]
  [0.8508461  0.45070984]
  [0.97932561 0.75700455]]

 [[0.44188321 0.0422673 ]
  [0.70958196 0.03680957]
  [0.05963609 0.7227017 ]]

 [[0.30653715 0.39631863]
  [0.106366   0.86739291]
  [0.60983612 0.24951634]]

 [[0.61022873 0.54218206]
  [0.77657673 0.11800927]
  [0.91551533 0.0432011 ]]]


In [38]:
#●	أمر choiceيختار قيمة عشوائية
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y)

print(a)


6


In [39]:
#●	ويمكن اختيار اكثر من قيمة  
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y, size = 5)

print(a)


[5 1 8 8 9]


In [40]:
#●	أمر shuffle  يعمل تغيير عشوائي في الترتيب 
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
print(y)

random.shuffle(y)

print(y)


[1, 2, 3, 6, 9, 8, 5, 4, 7, 8, 9, 6, 5, 9, 6]
[3, 2, 4, 8, 6, 5, 6, 8, 9, 6, 5, 9, 9, 7, 1]


In [41]:
#●	عمل مصفوفة اصفار او  وحايد  
a = zeros(8)
b = ones(10)

print(a)
print(b)


[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [42]:
#●	لو مطلوب بعدين (فيه قوسين في الاول و في الاخر )  
a = zeros((3,5))
b = ones((6,8))

print(a)
print(b)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
a = zeros((2,3,2))

b = ones((2,3,2))

print(a)
print(b)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [44]:
#●	مصفوفة الوحدة  
a = eye(5) 
print(a)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
#●	أمر full   بيعمل مصفوفة بنفس الرقم المعطي  
a = full((3, 5), 35)

print(a)


[[35 35 35 35 35]
 [35 35 35 35 35]
 [35 35 35 35 35]]


In [46]:
#●	و ممكن كتابة مصفوفة بابعاد محددة كدة
a =arange(18).reshape(3,6)
b =arange(27).reshape(3,3,3)

print(a)
print(b)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [47]:
#●	لكتابة ارقام متوزعة بالتساوي بين رقمين
b =linspace(0,30)
c =linspace(0,100,5)

print(b)
print(c)


[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
[  0.  25.  50.  75. 100.]


In [48]:
#●	لتحويلها لمصفوفة
b =linspace(0,30,12).reshape(3,4)
c =linspace(0,100,27).reshape(3,3,3)

print(b)
print(c)


[[ 0.          2.72727273  5.45454545  8.18181818]
 [10.90909091 13.63636364 16.36363636 19.09090909]
 [21.81818182 24.54545455 27.27272727 30.        ]]
[[[  0.           3.84615385   7.69230769]
  [ 11.53846154  15.38461538  19.23076923]
  [ 23.07692308  26.92307692  30.76923077]]

 [[ 34.61538462  38.46153846  42.30769231]
  [ 46.15384615  50.          53.84615385]
  [ 57.69230769  61.53846154  65.38461538]]

 [[ 69.23076923  73.07692308  76.92307692]
  [ 80.76923077  84.61538462  88.46153846]
  [ 92.30769231  96.15384615 100.        ]]]


In [49]:
#●	المصفوفة القطرية
a = diag (array([5,12,4,-1,3]))

b =diag  (array([5,12,4,-1,3]),  k=3 )

print(a)
print('-------------------------')
print(b)
print('-------------------------')


[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
-------------------------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
-------------------------


# التعامل مع المصفوفات


In [50]:
#●	ممكن حساب الارقام التي ليست صفر  
a = random.randint(0, 10, (3,3))
b = count_nonzero(a)


print(a)
print(b)


[[2 0 2]
 [6 8 5]
 [0 3 5]]
7


In [51]:
#●	او تحديد عدد الارقام اكبر او اصغر من كذا   
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a>5)
c = count_nonzero(a<8)

print(a)
print(b)
print(c)


[[1 5 2]
 [2 1 0]
 [9 5 0]]
1
8


In [52]:
#●	وممكن حساب الارقام يكون بالصف كله  
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a>5,axis=1)
c = count_nonzero(a<8,axis=1)

print(a)                               
print(b)
print(c)


[[4 0 2]
 [3 4 4]
 [9 7 8]]
[0 0 3]
[3 3 1]


In [53]:
#●	لمعرفة هل فيه رقم اكبر او اصغر من كذا ولا لا   
a = random.randint(0, 10, (3, 3))
b = any(a>5)
print(a)
print(b)


[[3 2 3]
 [4 2 0]
 [3 3 2]]
False


In [54]:
#●	ويمكن عملها في كل صف  
a = random.randint(0, 10, (3, 3))
b = any(a>5,axis=1)

print(a)
print(b)


[[8 9 6]
 [9 4 2]
 [5 0 7]]
[ True  True  True]


In [57]:
#●	ويمكن معرفة هل كل العناصر شرط معين
a = random.randint(0, 10, (3, 3))
b = all(a>5)

print(a)
print(b)


[[8 3 3]
 [0 0 6]
 [9 9 2]]
False


In [58]:
#●	ويمكن معرفة هل العناصر اكبر من او اصغر من رقم معين
a =random.randint(5,20, size=9).reshape(3,3)

b = a>10
c = a<15

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)


[[ 5 16  6]
 [17  9 14]
 [17  6 15]]
-------------------------
[[False  True False]
 [ True False  True]
 [ True False  True]]
-------------------------
[[ True False  True]
 [False  True  True]
 [False  True False]]


In [59]:
#●	مقارنة المصفوفات  
a =arange(9).reshape(3,3)
b =arange(9).reshape(3,3)
c = 2*b
d = isclose(a,b,rtol = 0.1)
e = isclose(a,c,rtol = 0.1)


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
-------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------------------
[[ True False False]
 [False False False]
 [False False False]]


In [60]:
#●	يمكن ضرب قيم المصفوفة في بعضها (ضرب الدوت)  
a =arange(5)
b =empty(5)

multiply(a, 10, out=b)

print(a)
print(b)        
#The code multiply(a, 10, out=b) in Python, specifically using the NumPy library, performs element-wise multiplication of the array a by the scalar value 10, and stores the result in the array b

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [61]:
#●	لرفع كل العناصر للأس الرابع  
a =arange(5)
b =empty(5)

power(a, 4, out=b)

print(a)
print(b)


[0 1 2 3 4]
[  0.   1.  16.  81. 256.]


In [62]:
#●	مجموع قيم المصفوفة  
a =arange(15)


b = add.reduce(a)

print(a)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105


In [63]:
#●	حاصل ضرب قيم المصفوفة 
a =arange(2,8)


b = multiply.reduce(a)

print(a)
print(b)


[2 3 4 5 6 7]
5040


In [64]:
#●	عملية ضرب متبادلة  
a =arange(2,8)                     #  row 3*cols 3  .  row 3*cols 4  =  row(1)3*colmn(2)4 #cols(1)==rows(2) 


b = multiply.outer(a,a)

print(a)
print(b)


[2 3 4 5 6 7]
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


In [66]:
#●	جمع كل الارقام السابقة  
a =arange(10)


b = add.accumulate(a)

print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


In [67]:
#●	ضرب الارقام السابقة  
a =arange(2,8)


b = multiply.accumulate(a)

print(a)
print(b)


[2 3 4 5 6 7]
[   2    6   24  120  720 5040]


In [68]:
#●	لمعرفة عدد عناصر المصفوفة , او عدد صفوفها لو اكتر من بعد
a =arange(12)
b = len(a)

c = a.reshape(3,4)
d = len(c)

print(a)
print(b)
print(c)
print(d)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3


In [69]:
#●	لمعرفة كل عدد عناصرها   
a =arange(12)
b = a.size

c = a.reshape(3,4)
d = c.size

print(a)
print(b)
print(c)
print(d)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12


In [10]:
#●	و هنا الابعاد بالتفصيل  
a =arange(12)
b = a.shape

c = a.reshape(3,4)
d = c.shape

print(a)
print(b)
print(c)
print(d)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [11]:
#●	عدد ابعادها  
a =arange(27)
b = a.ndim

c = a.reshape(3,3,3)
d = c.ndim

print(a)
print(b)
print(c)
print(d)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3


In [73]:
#●	نجمع قيم المحور  
a =arange(9)
b = a.reshape(3,3)
c = trace(b)


print(a)
print(b)
print(c)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [74]:
#●	قيمة المصفوفة 
a =arange(9)                                 #determinant 
b = a.reshape(3,3)           
c = linalg.det(b)                 #linalg
print(a)
print(b)
print(c)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0.0


# ●	الاقتطاع من المصفوفة  

In [84]:
a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]                    # ( start(0(n+1))      :      (end(n-1))    : step )
f = a[-1]                                      
g = a[-3]

print(a)
print(c)
print(d)
print(e)
print(f)
print(g)


[0 1 2 3 4 5 6 7 8 9]
3
[3 4 5 6 7 8]
[3 5 7]
9
7


In [85]:
a =arange(36).reshape(6,6)

c = a[3]                              # ( start(0(n+1))      :      (end(n-1))    : step )  
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
-------------------------
[30 31 32 33 34 35]
-------------------------
[18 19 20 21 22 23]


In [86]:
a =arange(36).reshape(6,6)

c = a[ 3 , 1 ]
d = a[ 3 , : ]                                          # ( start(0(n+1))       :      (end(n-1))    : step ) 
e = a[ : , 2 ]                                          # ( start(0(n+1))       :      (end(n-1))    : step ) 
f = a[ : , 1 : 3]
g = a[ 1 : 2  ,  :  ]

print(a) 
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)                                                                               

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
19
-------------------------
[18 19 20 21 22 23]
-------------------------
[ 2  8 14 20 26 32]
-------------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
-------------------------
[[ 6  7  8  9 10 11]]


In [87]:
a =arange(36).reshape(6,6)

c = a[3:4,1:5]
d = a[ 2 : , 3 : ]
e = a[ : 2 , : 3 ]
f = a[ : , -1 ]
g = a[ -1 , : ]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[19 20 21 22]]
-------------------------
[[15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
-------------------------
[[0 1 2]
 [6 7 8]]
-------------------------
[ 5 11 17 23 29 35]
-------------------------
[30 31 32 33 34 35]


In [89]:
#●	تعديل القيم  
a =arange(16).reshape(4,4)
print(a)
print('*********************************************')
a[2,3] = 0
print(a)
print('*********************************************')
a[:,3] = 0 
print(a)
print('*********************************************')
a[2,:] = 0 
print(a)
print('*********************************************')
a[:,:] = 0 
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
*********************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]
*********************************************
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]]
*********************************************
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 0  0  0  0]
 [12 13 14  0]]
*********************************************
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [90]:
#●	تحديد عنصر   
a =arange(16).reshape(4,4)

b = a[2][1]

print(a)
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
9


In [75]:
#●	الجمع و الطرح  
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a+b
d = a-b

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)


[[ 5  8 16]
 [ 5  5 14]
 [14 10  9]]
-------------------------
[[12 11  9]
 [12 17 12]
 [14 10  8]]
-------------------------
[[17 19 25]
 [17 22 26]
 [28 20 17]]
-------------------------
[[ -7  -3   7]
 [ -7 -12   2]
 [  0   0   1]]


In [76]:
#●	الضرب و القسمة  
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a*b
d = a/b

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)


[[11  7  9]
 [ 6 14 17]
 [17 12  8]]
-------------------------
[[14 13 19]
 [11  9  9]
 [19  7  7]]
-------------------------
[[154  91 171]
 [ 66 126 153]
 [323  84  56]]
-------------------------
[[0.78571429 0.53846154 0.47368421]
 [0.54545455 1.55555556 1.88888889]
 [0.89473684 1.71428571 1.14285714]]


In [77]:
#●	الضرب و القسمة  علي رقم
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a*3
d = b/5

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)


[[10 17 15]
 [ 5  7 12]
 [14  5  9]]
-------------------------
[[12  9  9]
 [ 8  5 14]
 [12  7  6]]
-------------------------
[[30 51 45]
 [15 21 36]
 [42 15 27]]
-------------------------
[[2.4 1.8 1.8]
 [1.6 1.  2.8]
 [2.4 1.4 1.2]]


In [78]:
#●	دوال للمصفوفة
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = sin(a)
d = b**2
e = log(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


[[16 10  7]
 [10 10  9]
 [13  5 16]]
-------------------------
[[ 8 12 13]
 [ 7 13 18]
 [ 6 13  9]]
-------------------------
[[-0.28790332 -0.54402111  0.6569866 ]
 [-0.54402111 -0.54402111  0.41211849]
 [ 0.42016704 -0.95892427 -0.28790332]]
-------------------------
[[ 64 144 169]
 [ 49 169 324]
 [ 36 169  81]]
-------------------------
[[2.77258872 2.30258509 1.94591015]
 [2.30258509 2.30258509 2.19722458]
 [2.56494936 1.60943791 2.77258872]]


In [92]:
#●	ضرب المصفوفات
a =random.randint(1,4, size=12).reshape(4,3)   #4*3     .   3*4
b =random.randint(1,4, size=12).reshape(3,4)


c = dot(a,b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)


[[2 2 1]
 [1 2 3]
 [2 2 2]
 [1 2 3]]
-------------------------
[[1 3 2 1]
 [2 2 2 3]
 [3 2 2 2]]
-------------------------
[[ 9 12 10 10]
 [14 13 12 13]
 [12 14 12 12]
 [14 13 12 13]]


In [80]:
#●	مجموع القيم  
a =random.randint(5,20, size=9).reshape(3,3)
b = sum(a)
c = a.sum()
d = a.sum(axis = 1)
e = a.sum(axis = 0)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


[[16 11  5]
 [18 13  5]
 [ 9  8  6]]
-------------------------
91
-------------------------
91
-------------------------
[32 36 23]
-------------------------
[43 32 16]


In [3]:
##●	معكوس المصفوفة  ##
from numpy import *
a =random.randint(1,4, size=9).reshape(3,3)
b =linalg.inv(a)
e=a.T
c = dot(a,b)

print(a)
print('-------------------------')
print(b)
print('*********************************************')
print(e)
print('*********************************************')
print(c)

[[3 2 2]
 [2 1 3]
 [2 3 2]]
-------------------------
[[ 0.77777778 -0.22222222 -0.44444444]
 [-0.22222222 -0.22222222  0.55555556]
 [-0.44444444  0.55555556  0.11111111]]
*********************************************
[[3 2 2]
 [2 1 3]
 [2 3 2]]
*********************************************
[[1.00000000e+00 0.00000000e+00 8.32667268e-17]
 [0.00000000e+00 1.00000000e+00 1.38777878e-17]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
